#!/bin/bash
#
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# If installation fails then we do not want to run tests
set -e


# eclipse2017/profile/app/app
APP_PATH=$(dirname $(dirname $PWD))

# eclipse2017/profile/
PROFILE_PATH=$(dirname $APP_PATH)

# eclipse2017/
PRJ_PATH=$(dirname $PROFILE_PATH)
BUILD_DIR=$PRJ_PATH/build

# common_tests/
COMMON_TEST_PATH=$PRJ_PATH/common_tests

# profile/tests/flask/lib
PROFILE_LIB_PATH=$PWD/lib
# common_tests/lib
COMMON_LIB_PATH=$COMMON_TEST_PATH/lib

export PYTHONPATH=/app:/app/profile/app
python -m unittest discover . "*_test.py"
