#!/bin/bash
#
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Running upload daemon tests...";

# Append directories to $PYTHONPATH
# DAEMON_DIR = movie/daemon - Used for app.<x> imports
# PRJ_DIR = eclipse2017  - Used for common.<x> imports
DAEMON_DIR=$(dirname $PWD)
PRJ_DIR=$(dirname $(dirname $DAEMON_DIR))

export PYTHONPATH=$DAEMON_DIR:$PRJ_DIR:$PYTHONPATH
export GEOS_DIR=/usr/local

python -m unittest discover . "*_test.py"
