#!/bin/bash
#
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Cleaning..."

GCR_PREFIX="gcr.io/$GCLOUD_PROJ_PREFIX${GCLOUD_PROJ_PREFIX:+"/"}$GCLOUD_PROJ"
IMAGES="nginx-lb-emulator \
        static-nginx \
        nginx-container \
        app-container \
        base-container"

remove_image() {
  if [ "$LOCAL_DEV" != "true" ]; then
    docker rmi -f $GCR_PREFIX/$1
  else
    docker rmi -f $1
  fi
}

for img in $IMAGES; do
  [[ -z $APP || $APP == $img ]] && remove_image $img
done

[ -d build/ ] && rm -rf build/
