#!/bin/bash
#
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e
echo "Pushing docker images..."

# command aliases
PUSHCMD="gcloud docker -- push"

# Gcloud values
GCR_PREFIX="gcr.io/$GCLOUD_PROJ_PREFIX${GCLOUD_PROJ_PREFIX:+"/"}$GCLOUD_PROJ"

IMAGES="base-container \
        admin-server \
        admin-nginx \
        profile-server \
        profile-nginx \
        static-nginx"
if [ "$UNRELEASED" == "true" ]; then
  IMAGES="$IMAGES \
          upload-server \
          upload-nginx \
          upload-daemon"
fi

for img in ${IMAGES}; do
  [[ -z $APP || $APP == $img ]] && $PUSHCMD $GCR_PREFIX/$img
done

[[ $CMD = systest ]] && $PUSHCMD $GCR_PREFIX/upload-system-tests

echo "Done."
