#!/bin/bash
#
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#set -e

if [ "$APP" != "" ]; then
	echo "NO TESTS RUN"
	exit 0
fi

# Common tests
COMMON_PASS=0
if [ "$APP" == "" ]; then
	echo; echo "=== Common tests ==="
	cd common_tests
	./run_tests
	COMMON_PASS=$?
	cd ..
fi


# Final result
echo
test $COMMON_PASS -eq 0 -a $UPLOAD_DAEMON_PASS -eq 0 -a \
     $UPLOAD_SERVER_PASS -eq 0 -a $PROFILE_PASS -eq 0 -a \
     $MOVIE_DAEMON_PASS -eq 0
if [ $? == 0 ]; then
    echo "ALL TESTS PASSED"
else
    echo "SOME TEST(S) FAILED"
fi
